[package]
name = "ganbare"
version = "0.6.0"
authors = ["Pyry Kontio <pyry.kontio@drasa.eu>"]

[dependencies]
diesel_codegen = {version = "0.10", default-features = false, features = ["postgres", "dotenv"] }
dotenv = "0.8"
ganbare_backend = { path = "ganbare_backend" }
chrono = { version = "0.2", features = ["rustc-serialize"]}
rand = "0.3"
rustc-serialize = "0.3"
pencil = { git = "https://github.com/golddranks/pencil", branch = "modifications_for_ganbare", default-features = false }
hyper = { version = "0.10" , default-features = false }
env_logger = "0.4"
log = "0.3"
lazy_static = "0.2"
time = "0.1"
handlebars ="0.25"
unicode-normalization = "0.1"
regex = "0.2"
tempdir = "0.3"
try_map = "0.2"
mime = "0.2"
url = "1.2"
multi_mut = "0.1"
cookie = { git = "https://github.com/golddranks/cookie-rs", branch = "experiments" }
typemap = "0.3"
error-chain = { git = "https://github.com/golddranks/error-chain", branch = "new_constructor"}
