[package]
name = "ganbare"
version = "0.2.0"
authors = ["Pyry Kontio <pyry.kontio@drasa.eu>"]

[dependencies]

dotenv = "0.8"
ganbare_backend = { path = "ganbare_backend" }
chrono = { version = "0.2", features = ["rustc-serialize"]}
rand = "0.3"
rustc-serialize = "0.3"
pencil = { git = "https://github.com/golddranks/pencil", branch = "modifications_for_ganbare" }
hyper = "0.9"
env_logger = "0.3"
log = "*"
lazy_static = "*"
time = "*"
handlebars = "0.16"
unicode-normalization = "*"
regex = "0.1"

[replace]
"pq-sys:0.2.4" = { git = "https://github.com/golddranks/pq-sys.git", rev = "af7d3a9b87298289422eb2e2919948902bdc0e80"}
