[package]
name = "ganbare"
version = "0.1.0"
authors = ["Pyry Kontio <pyry.kontio@drasa.eu>"]

[dependencies]
diesel = { version = "0.8", features = ["chrono"]}
diesel_codegen = {version = "0.8", default-features = false, features = ["postgres", "dotenv"] }
dotenv = "0.8"
dotenv_macros = "0.9"
rust-crypto = "0.2"
error-chain = { path = "../error-chain" }
clap = "2"
chrono = "0.2"
rpassword = "0.2"
rand = "0.3"
rustc-serialize = "0.3"
binary_macros = "0.1"
data-encoding = "1.1"
pencil = { path = "../pencil" }
hyper = "0.9"
env_logger = "0.3"
log = "*"
lazy_static = "*"
time = "*"
lettre = "0.6"
handlebars = "*"
mime = { path = "../mime.rs"}
mime_multipart = "*"

[replace]
"mime:0.2.2" = { path = "../mime.rs"}
