[package]
name = "ganbare"
version = "0.6.0"
authors = ["Pyry Kontio <pyry.kontio@drasa.eu>"]

[features]
specify_schema = ["ganbare_backend/specify_schema"]

[dependencies]
diesel_codegen = {version = "0.11", default-features = false, features = ["postgres", "dotenv"] }
dotenv = "0.8"
ganbare_backend = { path = "ganbare_backend" }
chrono = { version = "0.3", features = ["serde"]}
rand = "0.3"
pencil = { git = "https://github.com/golddranks/pencil", branch = "modifications_for_ganbare", default-features = false }
hyper = { version = "0.10" , default-features = false }
env_logger = "0.4"
log = "0.3"
lazy_static = "0.2"
handlebars ="0.25"
unicode-normalization = "0.1"
regex = "0.2"
tempdir = "0.3"
try_map = "0.2"
mime = "0.2"
url = "1.2"
multi_mut = "0.1"
cookie = { git = "https://github.com/golddranks/cookie-rs", branch = "experiments" }
typemap = "0.3"
error-chain = { git = "https://github.com/golddranks/error-chain", branch = "new_constructor", default-features = false }
r2d2 = "0.7"
r2d2-diesel = "0.11"
rust-crypto = "0.2"
lettre = "0.6"
data-encoding = "1.1"
time = "0.1"
serde_json = "0.9"

[replace]
"email:0.0.14" = { git = "https://github.com/golddranks/rust-email/" }
