[package]
name = "ganbare"
version = "0.1.0"
authors = ["Pyry Kontio <pyry.kontio@drasa.eu>"]

[dependencies]
ganbare_backend = { path = "ganbare_backend" }
dotenv = "0.8"
chrono = { version = "0.2", features = ["rustc-serialize"]}
rand = "0.3"
rustc-serialize = "0.3"
pencil = { git = "https://github.com/golddranks/pencil", branch = "modifications_for_ganbare" }
hyper = "0.9"
env_logger = "0.3"
log = "*"
lazy_static = "*"
time = "*"
handlebars = "0.16"
unicode-normalization = "*"
regex = "0.1"
